# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HAPDONG_Seminar_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HAPDONG_Seminar_Project
  pod 'Kingfisher', '~> 5.0'
  pod 'Alamofire', '~> 5.1'
  pod 'SwiftyJSON','~>4.0'
end
